services:
  - type: web
    name: mlsite
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: daphne -b 0.0.0.0 -p $PORT mlsite.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mlsite.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "mlsite.onrender.com"
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /
    autoDeploy: true 